env:
  browser: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
settings:
  react:
    version: "detect"
plugins:
  - "react"
  - "react-hooks"
  - "@typescript-eslint"
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:react-hooks/recommended"
  - "plugin:react/jsx-runtime"
  - "plugin:@typescript-eslint/recommended"
